2024-09-05 22:00:22,963 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-09-05 22:00:22,964 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\ELIXPO\Desktop\elixpo.ai\.venv\Lib\site-packages\instabot\bot\bot.py
2024-09-05 22:00:22,964 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-09-05 22:00:23,467 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2024-09-05 22:00:23,843 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2024-09-05 22:00:24,203 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2024-09-05 22:00:24,527 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2024-09-05 22:00:30,105 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2024-09-05 22:00:30,105 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXE_L6FoIfEE3Owl5mpnjhV3nJ-3eQ5UGfv8WGqAPqEmGvNGEBPoPVp23fTexzNq-7WUfPI/AfzHvzuyhGIDX50ggt2a8yeHNGtB-pAO4gJw5lKV-ISfxE_eLS06Af8G_BBtWxTrEzU6TGyxsF5wcA/","api_path":"/challenge/AXE_L6FoIfEE3Owl5mpnjhV3nJ-3eQ5UGfv8WGqAPqEmGvNGEBPoPVp23fTexzNq-7WUfPI/AfzHvzuyhGIDX50ggt2a8yeHNGtB-pAO4gJw5lKV-ISfxE_eLS06Af8G_BBtWxTrEzU6TGyxsF5wcA/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2024-09-05 22:00:30,106 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2024-09-05 22:00:30,106 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2024-09-05 22:00:30,107 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2024-09-05 22:00:32,149 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2024-09-05 22:00:32,149 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'temp_image.jpg' is not uploaded.
