2024-09-05 22:01:09,073 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-09-05 22:01:09,074 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\ELIXPO\Desktop\elixpo.ai\.venv\Lib\site-packages\instabot\bot\bot.py
2024-09-05 22:01:09,074 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-09-05 22:01:09,495 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2024-09-05 22:01:09,794 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2024-09-05 22:01:10,140 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2024-09-05 22:01:10,485 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2024-09-05 22:01:15,024 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2024-09-05 22:01:15,024 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXHlT-cxu73Db390a8kR522Q3_WXmY6tB1R6v1qRyOxg91Rcwy2Q4GCWZKXvcwMpYK6-G_g/AfxBtxu3Bx7IU5eyEc2il8xQckREn7i2VbnuP9HfCcF3zJZ1fhhRcK35Ezp3yIaFyNr0xuHBByeLow/","api_path":"/challenge/AXHlT-cxu73Db390a8kR522Q3_WXmY6tB1R6v1qRyOxg91Rcwy2Q4GCWZKXvcwMpYK6-G_g/AfxBtxu3Bx7IU5eyEc2il8xQckREn7i2VbnuP9HfCcF3zJZ1fhhRcK35Ezp3yIaFyNr0xuHBByeLow/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2024-09-05 22:01:15,024 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2024-09-05 22:01:15,025 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2024-09-05 22:01:15,025 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2024-09-05 22:01:17,517 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2024-09-05 22:01:17,519 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'temp_image.jpg' is not uploaded.
